"""Reconcile the stream with batch for one replayed day (ADR 0012).

Both sides count the same silver trips per pickup zone and hour:

- batch: the gold table ``hourly_pickup_zones``;
- stream: the 15-minute windows written by ``mobility-lakehouse stream``, added up per hour.

The stream may only miss trips, never invent them, and the trips it misses must be exactly the late events
Spark reported as dropped by the watermark. If both hold, every trip is accounted for.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import TYPE_CHECKING

from mobility_lakehouse.delta_io import PARTITION_COLUMN, Table

if TYPE_CHECKING:
    from pyspark.sql import SparkSession

Cell = tuple[int, int]  # (pickup hour, pickup zone ID)
MAX_CELLS = 24 * 300  # 24 hours x at most 265 TLC zones, with room to spare


@dataclass(frozen=True)
class Reconciliation:
    day: date
    batch_trips: int
    stream_trips: int
    dropped_late: int  # reported by Spark, summed over the stream runs
    runs: int
    cells: int  # (hour, zone) pairs present on either side
    cells_equal: int
    cells_short: int  # stream counted fewer trips than batch: expected for late events
    cells_over: int  # stream counted more trips than batch: never expected

    @property
    def missing(self) -> int:
        return self.batch_trips - self.stream_trips

    @property
    def reconciled(self) -> bool:
        return self.missing == self.dropped_late and self.cells_over == 0


def compare(
    day: date, batch: dict[Cell, int], stream: dict[Cell, int], dropped_late: int, runs: int
) -> Reconciliation:
    cells = set(batch) | set(stream)
    equal = short = over = 0
    for cell in cells:
        difference = stream.get(cell, 0) - batch.get(cell, 0)
        if difference == 0:
            equal += 1
        elif difference < 0:
            short += 1
        else:
            over += 1
    return Reconciliation(
        day=day,
        batch_trips=sum(batch.values()),
        stream_trips=sum(stream.values()),
        dropped_late=dropped_late,
        runs=runs,
        cells=len(cells),
        cells_equal=equal,
        cells_short=short,
        cells_over=over,
    )


def summary_lines(result: Reconciliation) -> list[str]:
    verdict = "RECONCILED" if result.reconciled else "NOT RECONCILED"
    return [
        f"Reconciliation {result.day}: {verdict}",
        f"  batch trips (gold hourly_pickup_zones): {result.batch_trips:>10,}",
        f"  stream trips (15-minute windows):       {result.stream_trips:>10,}",
        f"  missing from the stream:                {result.missing:>10,}",
        f"  dropped as too late (Spark, {result.runs} run(s)):  {result.dropped_late:>10,}",
        f"  zone-hours: {result.cells:,} in total, {result.cells_equal:,} equal, "
        f"{result.cells_short:,} short by late events, {result.cells_over:,} over",
    ]


def render_report(result: Reconciliation) -> str:
    """Markdown report, committed under docs/reports as evidence."""
    verdict = (
        "Every trip is accounted for: the trips missing from the stream are exactly the late events dropped "
        "by the watermark, and no zone-hour has more trips in the stream than in batch."
        if result.reconciled
        else "The stream and batch do not reconcile. See the numbers below."
    )
    share = 100 * result.missing / result.batch_trips if result.batch_trips else 0.0
    return f"""# Streaming reconciliation: {result.day}

Generated by `mobility-lakehouse reconcile --date {result.day}`
([ADR 0012](../adr/0012-streaming-replay-with-watermark.md)).

**Result: {"reconciled" if result.reconciled else "not reconciled"}.** {verdict}

| Measure | Value |
|---|---|
| Trips in batch (gold `hourly_pickup_zones`) | {result.batch_trips:,} |
| Trips in the stream (15-minute windows, added up per hour) | {result.stream_trips:,} |
| Missing from the stream | {result.missing:,} ({share:.2f}%) |
| Dropped as too late, reported by Spark | {result.dropped_late:,} |
| Stream runs | {result.runs} |
| Zone-hours compared | {result.cells:,} |
| Zone-hours equal | {result.cells_equal:,} |
| Zone-hours short (late events dropped) | {result.cells_short:,} |
| Zone-hours with more trips in the stream | {result.cells_over:,} |

The watermark is 30 minutes. Events sent more than about 30 minutes after their pickup time are dropped by
design: the window they belong to is already final.
"""


def batch_hourly(spark: SparkSession, hourly_pickup_zones: Table, day: date) -> dict[Cell, int]:
    from pyspark.sql import functions as F

    from mobility_lakehouse.tlc import Month

    rows = (
        hourly_pickup_zones.read(spark)
        .where(F.col(PARTITION_COLUMN) == F.lit(Month(day.year, day.month).start))
        .where(F.col("pickup_date") == F.lit(day))
        .groupBy("pickup_hour", "PULocationID")
        .agg(F.sum("trips").alias("trips"))
        .limit(MAX_CELLS)
        .collect()
    )
    return {(int(r["pickup_hour"]), int(r["PULocationID"])): int(r["trips"]) for r in rows}


def stream_hourly(spark: SparkSession, table_path: str, day: date) -> dict[Cell, int]:
    from pyspark.sql import functions as F

    rows = (
        spark.read.format("delta")
        .load(table_path)
        .where(F.to_date("window_start") == F.lit(day))
        .groupBy(F.hour("window_start").alias("pickup_hour"), "pickup_zone_id")
        .agg(F.sum("trips").alias("trips"))
        .limit(MAX_CELLS)
        .collect()
    )
    return {(int(r["pickup_hour"]), int(r["pickup_zone_id"])): int(r["trips"]) for r in rows}


def dropped_in_runs(spark: SparkSession, runs_path: str) -> tuple[int, int]:
    """(late rows dropped, number of runs) over every recorded stream run."""
    from pyspark.sql import functions as F

    row = (
        spark.read.format("delta")
        .load(runs_path)
        .agg(F.sum("dropped_late_rows").alias("dropped"), F.count(F.lit(1)).alias("runs"))
        .first()
    )
    return int(row["dropped"] or 0), int(row["runs"])
